services:
  # Your existing services (db, redis, web)
  db_main:
    image: postgres:15.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${ALGO_RUMBLE_PASSWORD}
      POSTGRES_DB: ${ALGO_RUMBLE_DB}
    ports:
      - ${ALGO_RUMBLE_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - algo_rumble_data:/var/lib/postgresql/data/


  redis:
    image: redis:7.4.2
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_SERVER_PORT}:8000
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db_main:
        condition: service_healthy



volumes:
  algo_rumble_data:
