services:
  # Your existing services (db, redis, web)
  db_main:
    image: postgres:15.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${ALGO_RUMBLE_PASSWORD}
      POSTGRES_DB: ${ALGO_RUMBLE_DB}
    ports:
      - ${ALGO_RUMBLE_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - algo_rumble_data:/var/lib/postgresql/data/

  db_judge0:
    image: postgres:15.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${JUDGE0_DB_PASSWORD}
      POSTGRES_DB: ${JUDGE0_DB}
    ports:
      - ${JUDGE0_DB_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - judge0_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.4.2
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_SERVER_PORT}:8000
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db_main:
        condition: service_healthy
      db_judge0:
        condition: service_healthy

  judge0-server:
    image: judge0/judge0:1.13.1
    platform: ${PLATFORM}
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - ${JUDGE0_SERVER_PORT}:2358
    privileged: true
    environment:
      POSTGRES_HOST: ${JUDGE0_DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${JUDGE0_DB_PASSWORD}
      POSTGRES_DB: ${JUDGE0_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      db_judge0:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  judge0-workers:
    image: judge0/judge0:1.13.1
    platform: ${PLATFORM}
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    command: [ "./scripts/workers" ]
    privileged: true
    environment:
      POSTGRES_HOST: ${JUDGE0_DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${JUDGE0_DB_PASSWORD}
      POSTGRES_DB: ${JUDGE0_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      db_judge0:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

volumes:
  algo_rumble_data:
  judge0_data: