#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE judge0;
    CREATE USER judge0 WITH PASSWORD '$JUDGE0_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE judge0 TO judge0;

    -- Don't create main DB here - let Docker's POSTGRES_DB handle it
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL
